_commit: v1.6.0
_src_path: gh:superlinear-ai/substrate
author_email: travis.j.hathaway@gmail.com
author_name: Travis Hathaway
project_description: A map for events during ADE 2025
project_name: ADE Mapper
project_type: app
project_url: https://github.com/travishathaway/ade-mapper
python_version: '3.10'
typing: strict
with_conventional_commits: true
with_fastapi_api: false
with_typer_cli: true
